replicaCount: 1

image:
  repository: lscr.io/linuxserver/qbittorrent
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

env:
  - name: PUID
    value: "1000"
  - name: PGID
    value: "1000"
  - name: TZ
    value: "Etc/UTC"
  - name: WEBUI_PORT
    value: "8080"

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  enabled: true
  port: 8080
  type: ClusterIP

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "cert-cluster-issuer"
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: qbittorrent.cbxon.co.uk
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: qbittorrent-tls
      hosts:
        - qbittorrent.cbxon.co.uk

resources: {}

livenessProbe: {}
readinessProbe: {}
lifecycle: {}

volumes:
  - name: wg-config
    secret:
      secretName: wg-conf
  - name: port-config
    emptyDir:
      sizeLimit: 500Mi
volumeMounts:
  - name: port-config
    mountPath: "/natpmp/"

nodeSelector: {}

tolerations: []

affinity: {}

sidecar:
  enabled: true
  image: "ghcr.io/cbx0n/wgpmp:latest"
  securityContext:
    privileged: true
    capabilities:
      add: ["NET_ADMIN"]
  volumeMounts:
    - name: wg-config
      readOnly: true
      mountPath: "/etc/wireguard"
    - name: port-config
      mountPath: "/natpmp/"