replicaCount: 1

image:
  repository: qmcgaw/gluetun
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

env: {}

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext:
  privileged: true
  capabilities:
    add: ["NET_ADMIN"]

service:
  enabled: true
  port: 9999
  type: ClusterIP

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts: []
  tls: []

resources: {}

livenessProbe: {}
readinessProbe:
  httpGet:
    port: 9999
    path: /v1/health
  initialDelaySeconds: 15
  periodSeconds: 10
lifecycle:
  postStart:
    exec:
      command: ["/bin/sh", "-c", "(ip rule del table 51820; ip -6 rule del table 51820) || true"]

volumes: []
volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}
