{{- range $name, $class := .Values.priortyClasses }}
{{- if and $class.enabled $class.enabled }}
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ $name }}
value: {{ .value }}
globalDefault: false
description:  {{ .description }}
{{- end }}
{{- end }}