{{- range $name, $svc := .Values.services }}
{{- if $svc.enabled }}
{{- range $svc.volumes }}
{{- if eq .type "pvc" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $name }}-{{ .name }}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .size }}
---
{{- end }}
{{- end }}
{{- end }}
{{- end }}
