{{- range $name, $svc := .Values.services }}
{{- if $svc.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  labels:
    app: {{ $name }}
spec:
  type: {{ default "ClusterIP" $svc.service.type }}
  selector:
    app: {{ $name }}
  ports:
{{- range $svc.ports }}
    - name: {{ .name }}
      port: {{ .containerPort }}
      targetPort: {{ .containerPort }}
      protocol: {{ default "TCP" .protocol }}
{{- end }}
---
{{- end }}
{{- end }}
