replicaCount: 1

image:
  repository: jellyfin/jellyfin
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

env:
  - name: PUID
    value: "1000"
  - name: PGID
    value: "1000"
  - name: TZ
    value: "Etc/UTC"

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  enabled: true
  port: 8096
  type: ClusterIP

ingress:
  enabled: false
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "cert-cluster-issuer"
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts: []
  tls: []

resources: {}

livenessProbe: {}
readinessProbe: {}
lifecycle: {}

volumes: []
volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}
