sonarr:
  enabled: true
  ingress:
    enabled: true
    hosts:
      - host: sonarr.cbxon.co.uk
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: sonarr-tls
        hosts:
          - sonarr.cbxon.co.uk
  
radarr:
  enabled: true
  ingress:
    enabled: true
    hosts:
      - host: radarr.cbxon.co.uk
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: radarr-tls
        hosts:
          - radarr.cbxon.co.uk

flaresolverr:
  enabled: true

prowlarr:
  enabled: true
  ingress:
    enabled: true
    hosts:
      - host: prowlarr.cbxon.co.uk
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: prowlarr-tls
        hosts:
          - prowlarr.cbxon.co.uk

qbittorrent:
  enabled: true
  ingress:
    enabled: true
    hosts:
      - host: qbittorrent.cbxon.co.uk
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: qbittorrent-tls
        hosts:
          - qbittorrent.cbxon.co.uk

jellyfin:
  enabled: true
  ingress:
    enabled: true
    hosts:
      - host: jellyfin.cbxon.co.uk
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: jellyfin-tls
        hosts:
          - jellyfin.cbxon.co.uk

jellyseerr:
  enabled: true
  ingress:
    enabled: true
    hosts:
      - host: jellyseerr.cbxon.co.uk
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: jellyseerr-tls
        hosts:
          - jellyseerr.cbxon.co.uk