sonarr:
  enabled: true
  
radarr:
  enabled: true

flaresolverr:
  enabled: true

prowlarr:
  enabled: true
  volumes:
    - name: rules
      configMap:
        name: indexer-ipconf
  sidecar:
    enabled: true
    image: ghcr.io/cbx0n/iptables:0.1.1
    securityContext:
      privileged: true
      capabilities:
        add: ["NET_ADMIN"]
    volumeMounts:
    - name: rules
      mountPath: /rules
      readOnly: true

gluetun:
  enabled: true
  env:
    - name: VPN_SERVICE_PROVIDER
      value: "custom"
    - name: VPN_PORT_FORWARDING_PROVIDER
      value: "protonvpn"
    - name: VPN_TYPE
      value: "wireguard"
    - name: VPN_PORT_FORWARDING
      value: "on"
    - name: TZ
      value: "Europe/London"
    - name: DOT
      value: "off"
    - name: HEALTH_SERVER_ADDRESS
      value: "0.0.0.0:9999"
    - name: VPN_INPUT_PORTS
      value: "0:65535"
    - name: VPN_OUTPUT_PORTS
      value: "0:65535"
    - name: FIREWALL
      value: "off"   # (optional) lets you manage iptables yourself


  volumes: 
    - name: wg-conf
      secret:
        secretName: wg-conf

  volumeMounts:
    - name: wg-conf
      mountPath: gluetun/wireguard/
      readOnly: true