replicaCount: 1

image:
  repository: ghcr.io/flaresolverr/flaresolverr
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8191

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts: []
  tls: []

resources: {}

livenessProbe: {}
readinessProbe: {}

volumes: []
volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}
