replicaCount: 1

image:
  repository: linuxserver/prowlarr
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

env: {}

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  enabled: true
  port: 9696
  type: ClusterIP

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "cert-cluster-issuer"
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: prowlarr.cbxon.co.uk
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: prowlarr-tls
      hosts:
        - prowlarr.cbxon.co.uk

resources: {}

livenessProbe: {}
readinessProbe: {}
lifecycle: {}

volumes: []
volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}

sidecar:
  enabled: false
  image: ""
  securityContext: {}
  volumeMounts: []