replicaCount: 1

image:
  repository: linuxserver/radarr
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

env: {}

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  enabled: true
  port: 7878
  type: ClusterIP

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "cert-cluster-issuer"
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: radarr.cbxon.co.uk
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: radarr-tls
      hosts:
        - radarr.cbxon.co.uk

resources: {}

livenessProbe: {}
readinessProbe: {}
lifecycle: {}

volumes: []
volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}
