replicaCount: 1

image:
  repository: linuxserver/radarr
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

env: {}

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  enabled: true
  port: 7878
  type: ClusterIP

ingress:
  enabled: false
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "cert-cluster-issuer"
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts: []
  tls: []

resources: {}

livenessProbe: {}
readinessProbe: {}
lifecycle: {}

volumes: []
volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}
